on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/ci.yml

      - name: Publish
        run: bash ./gradlew publishMod
        env:
          CURSE_TOKEN: ${{ secrets.CURSE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
